export const clubs = [
    {"name": "Real Madrid", "nation": "Spain", "pot": 1},
    {"name": "Man City", "nation": "England", "pot": 1},
    {"name": "Bayern Munchen", "nation": "Germany", "pot": 1},
    {"name": "Paris", "nation": "France", "pot": 1},
    {"name": "Liverpool", "nation": "England", "pot": 1},
    {"name": "Inter", "nation": "Italy", "pot": 1},
    {"name": "B.Dortmund", "nation": "Germany", "pot": 1},
    {"name": "Leipzig", "nation": "Germany", "pot": 1},
    {"name": "Barcelona", "nation": "Spain", "pot": 1},
    {"name": "Leverkusen", "nation": "Germany", "pot": 2},
    {"name": "Atleti", "nation": "Spain", "pot": 2},
    {"name": "Atalanta", "nation": "Italy", "pot": 2},
    {"name": "Juventus", "nation": "Italy", "pot": 2},
    {"name": "Benfica", "nation": "Portugal", "pot": 2},
    {"name": "Arsenal", "nation": "England", "pot": 2},
    {"name": "Club Brugge", "nation": "Belgium", "pot": 2},
    {"name": "Shakhtar", "nation": "Ukraine", "pot": 2},
    {"name": "Milan", "nation": "Italy", "pot": 2},
    {"name": "Feyenoord", "nation": "Netherlands", "pot": 3},
    {"name": "Sporting CP", "nation": "Portugal", "pot": 3},
    {"name": "PSV", "nation": "Netherlands", "pot": 3},
    {"name": "GNK Dinamo", "nation": "Croatia", "pot": 3},
    {"name": "Salzburg", "nation": "Austria", "pot": 3},
    {"name": "Lille", "nation": "France", "pot": 3},
    {"name": "Crvena Zvezda", "nation": "Serbia", "pot": 3},
    {"name": "Young Boys", "nation": "Switzerland", "pot": 3},
    {"name": "Celtic", "nation": "Scotland", "pot": 3},
    {"name": "S.Bratislava", "nation": "Slovakia", "pot": 4},
    {"name": "Monaco", "nation": "France", "pot": 4},
    {"name": "Sparta Praha", "nation": "Czech Republic", "pot": 4},
    {"name": "Aston Villa", "nation": "England", "pot": 4},
    {"name": "Bologna", "nation": "Italy", "pot": 4},
    {"name": "Girona", "nation": "Spain", "pot": 4},
    {"name": "Stuttgart", "nation": "Germany", "pot": 4},
    {"name": "Sturm Graz", "nation": "Austria", "pot": 4},
    {"name": "Brest", "nation": "France", "pot": 4}
]
export const matches = {
    "Real Madrid": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Man City": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Bayern Munchen": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Paris": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Liverpool": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Inter": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "B.Dortmund": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Leipzig": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Barcelona": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Leverkusen": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Atleti": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Atalanta": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Juventus": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Benfica": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Arsenal": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Club Brugge": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Shakhtar": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Milan": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Feyenoord": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Sporting CP": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "PSV": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "GNK Dinamo": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Salzburg": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Lille": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Crvena Zvezda": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Young Boys": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Celtic": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "S.Bratislava": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Monaco": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Sparta Praha": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Aston Villa": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Bologna": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Girona": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Stuttgart": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Sturm Graz": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" },
    "Brest": { "pot1H": "", "pot1A": "", "pot2H": "", "pot2A": "", "pot3H": "", "pot3A": "", "pot4H": "", "pot4A": "" }
}
